package com.cox.cox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerWithTreatment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer accountID;
	private java.lang.String name;
	private java.util.Date activationDate;
	private java.lang.Integer monthlyRecurringCharge;
	private java.lang.String status;
	private java.lang.String treatment;

	public CustomerWithTreatment() {
	}

	public java.lang.Integer getAccountID() {
		return this.accountID;
	}

	public void setAccountID(java.lang.Integer accountID) {
		this.accountID = accountID;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.Date getActivationDate() {
		return this.activationDate;
	}

	public void setActivationDate(java.util.Date activationDate) {
		this.activationDate = activationDate;
	}

	public java.lang.Integer getMonthlyRecurringCharge() {
		return this.monthlyRecurringCharge;
	}

	public void setMonthlyRecurringCharge(
			java.lang.Integer monthlyRecurringCharge) {
		this.monthlyRecurringCharge = monthlyRecurringCharge;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getTreatment() {
		return this.treatment;
	}

	public void setTreatment(java.lang.String treatment) {
		this.treatment = treatment;
	}

	public CustomerWithTreatment(java.lang.Integer accountID,
			java.lang.String name, java.util.Date activationDate,
			java.lang.Integer monthlyRecurringCharge, java.lang.String status,
			java.lang.String treatment) {
		this.accountID = accountID;
		this.name = name;
		this.activationDate = activationDate;
		this.monthlyRecurringCharge = monthlyRecurringCharge;
		this.status = status;
		this.treatment = treatment;
	}

}