package com.cox.cox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerTableList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.cox.cox.CustomerTable> customerTable;

	public CustomerTableList() {
	}

	public java.util.List<com.cox.cox.CustomerTable> getCustomerTable() {
		return this.customerTable;
	}

	public void setCustomerTable(
			java.util.List<com.cox.cox.CustomerTable> customerTable) {
		this.customerTable = customerTable;
	}

	public CustomerTableList(
			java.util.List<com.cox.cox.CustomerTable> customerTable) {
		this.customerTable = customerTable;
	}

}