package com.cox.cox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerNodeTableList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.cox.cox.CustomerNodeTable> customerNodeTableList;

	public CustomerNodeTableList() {
	}

	public java.util.List<com.cox.cox.CustomerNodeTable> getCustomerNodeTableList() {
		return this.customerNodeTableList;
	}

	public void setCustomerNodeTableList(
			java.util.List<com.cox.cox.CustomerNodeTable> customerNodeTableList) {
		this.customerNodeTableList = customerNodeTableList;
	}

	public CustomerNodeTableList(
			java.util.List<com.cox.cox.CustomerNodeTable> customerNodeTableList) {
		this.customerNodeTableList = customerNodeTableList;
	}

}