package com.cox.cox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerNodeTable implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer customerID;
	private java.lang.String customerNode;

	public CustomerNodeTable() {
	}

	public java.lang.Integer getCustomerID() {
		return this.customerID;
	}

	public void setCustomerID(java.lang.Integer customerID) {
		this.customerID = customerID;
	}

	public java.lang.String getCustomerNode() {
		return this.customerNode;
	}

	public void setCustomerNode(java.lang.String customerNode) {
		this.customerNode = customerNode;
	}

	public CustomerNodeTable(java.lang.Integer customerID,
			java.lang.String customerNode) {
		this.customerID = customerID;
		this.customerNode = customerNode;
	}

}