package com.cox.cox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerWithTreatmentList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.cox.cox.CustomerWithTreatment> customerWithTreatmentList;

	public CustomerWithTreatmentList() {
	}

	public java.util.List<com.cox.cox.CustomerWithTreatment> getCustomerWithTreatmentList() {
		return this.customerWithTreatmentList;
	}

	public void setCustomerWithTreatmentList(
			java.util.List<com.cox.cox.CustomerWithTreatment> customerWithTreatmentList) {
		this.customerWithTreatmentList = customerWithTreatmentList;
	}

	public CustomerWithTreatmentList(
			java.util.List<com.cox.cox.CustomerWithTreatment> customerWithTreatmentList) {
		this.customerWithTreatmentList = customerWithTreatmentList;
	}

}