package com.cox.cox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerIDList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.Integer> customerIDList;

	public CustomerIDList() {
	}

	public java.util.List<java.lang.Integer> getCustomerIDList() {
		return this.customerIDList;
	}

	public void setCustomerIDList(
			java.util.List<java.lang.Integer> customerIDList) {
		this.customerIDList = customerIDList;
	}

	public CustomerIDList(java.util.List<java.lang.Integer> customerIDList) {
		this.customerIDList = customerIDList;
	}

}