package com.cox.cox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IssueWithNotifyInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.time.LocalDateTime startDateTime;
	private java.time.LocalDateTime endDateTime;
	private java.lang.String node;
	private java.lang.Boolean notifiable;

	public IssueWithNotifyInfo() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.time.LocalDateTime getStartDateTime() {
		return this.startDateTime;
	}

	public void setStartDateTime(java.time.LocalDateTime startDateTime) {
		this.startDateTime = startDateTime;
	}

	public java.time.LocalDateTime getEndDateTime() {
		return this.endDateTime;
	}

	public void setEndDateTime(java.time.LocalDateTime endDateTime) {
		this.endDateTime = endDateTime;
	}

	public java.lang.String getNode() {
		return this.node;
	}

	public void setNode(java.lang.String node) {
		this.node = node;
	}

	public java.lang.Boolean getNotifiable() {
		return this.notifiable;
	}

	public void setNotifiable(java.lang.Boolean notifiable) {
		this.notifiable = notifiable;
	}

	public IssueWithNotifyInfo(java.lang.String type,
			java.time.LocalDateTime startDateTime,
			java.time.LocalDateTime endDateTime, java.lang.String node,
			java.lang.Boolean notifiable) {
		this.type = type;
		this.startDateTime = startDateTime;
		this.endDateTime = endDateTime;
		this.node = node;
		this.notifiable = notifiable;
	}

}