package com.cox.cox;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IssueWithNotifyInfoList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.cox.cox.IssueWithNotifyInfo issueWithNotifyInfoList;

	public IssueWithNotifyInfoList() {
	}

	public com.cox.cox.IssueWithNotifyInfo getIssueWithNotifyInfoList() {
		return this.issueWithNotifyInfoList;
	}

	public void setIssueWithNotifyInfoList(
			com.cox.cox.IssueWithNotifyInfo issueWithNotifyInfoList) {
		this.issueWithNotifyInfoList = issueWithNotifyInfoList;
	}

	public IssueWithNotifyInfoList(
			com.cox.cox.IssueWithNotifyInfo issueWithNotifyInfoList) {
		this.issueWithNotifyInfoList = issueWithNotifyInfoList;
	}

}